In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [59]:
df = pd.read_csv('razvod1.csv', sep=';', encoding='ansi')

In [60]:
df.head()

,Субъект РФ,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Российская Федерация,559 918,597 930,639 248,663 282,680 494,665 904,562 373,555 160,501 654,...,669 376,644 101,667 971,693 730,611 646,608 336,611 436,583 942,620 730,564 704
1,Центральный федеральный округ,153 624,161 194,171 040,182 178,184 195,179 835,158 578,155 350,143 687,...,174 079,166 889,175 840,178 701,161 463,159 704,162 939,153 515,168 393,147 979
2,Белгородская область,5 176,5 354,6 042,6 574,7 271,7 300,6 558,6 203,5 529,...,6 978,6 916,7 718,7 654,6 774,6 787,6 782,6 753,6 519,6 345
3,Брянская область,5 172,5 733,6 574,7 036,7 695,7 795,5 685,5 754,3 939,...,6 586,6 649,5 908,7 121,5 883,5 804,5 529,5 401,5 406,5 173
4,Владимирская область,5 637,6 110,7 025,7 507,7 678,7 799,5 691,5 762,4 718,...,6 745,6 485,6 945,6 795,5 861,5 592,5 798,5 508,5 503,4 771

In [62]:
df.dtypes

Субъект РФ    object
1990          object
1991          object
1992          object
1993          object
1994          object
1995          object
1996          object
1997          object
1998          object
1999          object
2000          object
2001          object
2002          object
2003          object
2004          object
2005          object
2006          object
2007          object
2008          object
2009          object
2010          object
2011          object
2012          object
2013          object
2014          object
2015          object
2016          object
2017          object
2018          object
2019          object
2020          object
dtype: object

Тут проблема в том, что все элементы таблицы - object

In [30]:
df.rename(columns = {'subject' : 'Subject'}, inplace = True)

In [56]:
df_cfo = pd.Series(df.iloc[1].T)

In [57]:
df_cfo

Subject        Центральный федеральный округ
1990                                 153 624
1991                                 161 194
1992                                 171 040
1993                                 182 178
1994                                 184 195
1995                                 179 835
1996                                 158 578
1997                                 155 350
1998                                 143 687
1999                                 147 954
2000                                 172 098
2001                                 204 060
2002                                 220 839
2003                                 202 864
2004                                 170 864
2005                                 162 804
2006                                 167 353
2007                                 179 574
2008                                 186 234
2009                                 186 845
2010                                 169 508
2011                                 174 079
2012                                 166 889
2013                                 175 840
2014                                 178 701
2015                                 161 463
2016                                 159 704
2017                                 162 939
2018                                 153 515
2019                                 168 393
2020                                 147 979
Name: 1, dtype: object